name: 'thank you action'
description: 'say "thankyou" to new pull requests'
author: 'Elida wanjiku'

inputs:
   GITHUB_TOKEN:
      description: 'Github token'
      required: true
   TENOR_TOKEN:
      description: 'Tenor API token'
      required: true
runs:
   using: 'node12'
   main: 'dist/index.js'
